// <auto-generated />
using BlazorPiano.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorPiano.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231115132912_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorPiano.Shared.Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LessonDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Details1");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "I am a classically trained musician who has been teaching for over 6 years. I teach casual learners and for ABRSM exams. Styles include classical, contemporary, blues/jazz.",
                            ImageUrl = "https://lh3.googleusercontent.com/p/AF1QipP-QQbhWJCGSqHx_Ov9sb0UI33q7gTd-guRmVct=s680-w680-h510",
                            LessonDetails = "All ages from 6 to retirement are welcome. Teaching rate: £32.00 per hour Current teaching days in Great Dunmow: Wednesday, Thursday Current availability in Great Dunmow: Thursday 3:30pm-4:00pm and 4:00pm-4:30pm. I can also accommodate fortnightly lessons, please contact for availability. Current teaching days in Bishop Stortford: Monday, Tuesday, Friday, Saturday Current availability in Bishop Stortford: Please contact",
                            Name = "Becky"
                        });
                });

            modelBuilder.Entity("BlazorPiano.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A single half hour lesson",
                            ImageUrl = "https://images.unsplash.com/photo-1571974599782-87624638275e?q=80&w=1931&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 20.99m,
                            Title = "One Lesson"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Two half hour lessons",
                            ImageUrl = "https://images.unsplash.com/photo-1571974599782-87624638275e?q=80&w=1931&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 30.99m,
                            Title = "Two Lessons"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Three half hour lessons",
                            ImageUrl = "https://images.unsplash.com/photo-1571974599782-87624638275e?q=80&w=1931&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 35.99m,
                            Title = "Three Lessons"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
